name: Moderate Confessions
on:
  repository_dispatch:
    types: [state-updated]
jobs:
  mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python -m pip install --upgrade pip
          pip install profanity-check langdetect
          python scripts/moderator.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with: { commit_message: "feat: moderation pass" }
