name: Publish to X
on:
  schedule: [{ cron: "5,25,45 * * * *" }]
jobs:
  x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python -m pip install tweepy
          python scripts/post_x.py
